spring:
  application:
    name: model-webflux

 # r2dbc:
 #   url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
 #   username: sa
 #   password:
 # sql:
 #   init:
 #     mode: always
 #     schema-locations: classpath:schema.sql


  data:
    mongodb:
      host: localhost
      port: 27017
      database: springWebFlux
      username: teste
      password: teste123
      authentication-database: springWebFlux

springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: openapi_3_0



