spring:
  application:
    name: model-webflux

 # r2dbc:
 #   url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
 #   username: sa
 #   password:
 # sql:
 #   init:
 #     mode: always
 #     schema-locations: classpath:schema.sql


  data:
    mongodb:
      host: localhost
      port: 27017
      database: springWebFlux
      username: teste
      password: teste123
      authentication-database: springWebFlux

springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: openapi_3_0

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: group-multitopic
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

